AWSTemplateFormatVersion: "2010-09-09"
Description: "Amazon DynamoDb."
Resources:
  booksTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: "Retain"
    Properties:
        TableName: "Books"
        ProvisionedThroughput: 
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
        AttributeDefinitions:
            - 
                AttributeName: "Isbn"
                AttributeType: "S"
         
        KeySchema: 
            - 
                AttributeName: "Isbn"
                KeyType: "HASH"
