AWSTemplateFormatVersion: "2010-09-09"
Description: "Amazon EC2."
Resources:
    Host:
        Type: 'AWS::EC2::Host'
        Properties: 
            AutoPlacement: 'on'
            AvailabilityZone: us-east-1a
            InstanceType: t2.micro