AWSTemplateFormatVersion: "2010-09-09"
Description: "Amazon EC2 Instance"
Resources:
    EC2Instance:
        Type: "AWS::EC2::Instance"
        Properties:
            ImageId: "ami-08c40ec9ead489470"
            InstanceType: "t2.micro"
            AvailabilityZone: us-east-1a
            Tenancy: "default"
            EbsOptimized: false
            SourceDestCheck: true
            BlockDeviceMappings: 
              - 
                DeviceName: "/dev/sda1"
                Ebs: 
                    Encrypted: false
                    VolumeSize: 15
                    VolumeType: "gp2"
                    DeleteOnTermination: true
            Tags: 
              - 
                Key: "Name"
                Value: "AWSTaskEC2Instance"
            HibernationOptions: 
                Configured: false
            EnclaveOptions: 
                Enabled: false

