AWSTemplateFormatVersion: '2010-09-09'
Description: "An AWS Lambda template."
Resources:
    LambdaZipsBucket:
        Type: AWS::S3::Bucket
    CopyZips:
        Type: Custom::CopyZips
        Properties:
          ServiceToken: !GetAtt 'CopyZipsFunction.Arn'
          DestBucket: !Ref 'LambdaZipsBucket'
          SourceBucket: !Ref 'QSS3BucketName'
          Prefix: !Ref 'QSS3KeyPrefix'
          Objects:
            - functions/packages/LambdaFunction/lambda.zip

    LambdaFunction:
       Type: 'AWS::Lambda::Function'
       Properties:
          Description: ""
          Handler: 'AWSLambda::AWSLambda.Function::FunctionHandler'
          FunctionName: "aws-task-lambda-kep-tmp"
          Architectures: 
              - "x86_64"
          Code: 
            S3Bucket: !Ref 'LambdaZipsBucket'
            S3Key: !Sub '${QSS3KeyPrefix}functions/packages/LambdaFunction/lambda.zip'
          MemorySize: 512
          Runtime: "dotnet6"
          Timeout: 15
          TracingConfig: 
              Mode: "PassThrough"
          EphemeralStorage: 
              Size: 512
          Role: >-
            arn:aws:iam::042072295322:role/service-role/aws-task-lambda-kep-role-fq9dsxam

    LambdaEventSourceMapping:
        Type: "AWS::Lambda::EventSourceMapping"
        Properties:
            BatchSize: 10
            EventSourceArn: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:booksQueue"
            FunctionName: !GetAtt LambdaFunction.Arn
            Enabled: true
            MaximumBatchingWindowInSeconds: 0